### ISSUE TITLE
Disallow publishing if there are unpushed changes

### ISSUE THREAD

**Issue by adamlogic** [edgecase/middleman-gh-pages#3]
It's possible right now to publish a site without pushing up your master branch. I can't think of a scenario where this should be allowed.

**Comment by rmm5t** [comment]
> I can't think of a scenario where this should be allowed.

I actually do this on occasion, albeit rarely. I might have local commits that I haven't pushed yet, because I'm testing something new. I might just want to get this _unshared_ branch published to quickly test something before pushing to origin/master.

Conversely, I can't really think of a scenario where this shouldn't be allowed. It's true that it would be possible to have a gh-pages branch that never has an associated commit on the master branch, but that seems like more of a user-error than something this project should prevent against. After all, we can't prevent someone from force pushing to the origin/master. 

I understand this might be considered dangerous in some scenarios, but I wouldn't want this project to limit my ability to do this, even if I accidentally shoot myself in the foot. With power, comes responsibility, etc. Plus, because the gh-pages branch is always generated, it's not too difficult to recover from possible mistakes.
