### ISSUE TITLE
Deployed, but won't read CSS

### ISSUE THREAD

**Issue by andy4thehuynh** [edgecase/middleman-gh-pages#31]
I'm at andy4thehuynh.github.io/big4referral. Awesome!

However, I check the sources and my style.css file is completely empty. In my repo, I have content in my style.css:

https://github.com/andy4thehuynh/big4referral/blob/gh-pages/stylesheets/styles.css

Any idea why it won't read my css?

**Comment by rmm5t** [comment]
I don't think this is related to this project. Looking at your gh-pages branch, things look like they're generating just fine. However, it does look like you're using relative paths to your stylesheets instead of absolute paths (starting with `/`). That might be related to your problem, but for `index.html`, it should still work as expected.

**Comment by AgentEm** [comment]
Hi, I'm having the same issue with https://github.com/AgentEm/new-personal-site/tree/gh-pages. Seeing all of the files there properly, working locally, I can successfully rake publish but the css and image files aren't there.

**Comment by rmm5t** [comment]
@AgentEm Since you don't have a `CNAME` file in your repository, I presume, you're running this site under the GitHub convention of: http://agentem.github.io/new-personal-site/

Middleman assumes (and prefers) that you're always running a site at the root of the domain. If you want to run it in a subdirectory, you'll need to enable relative links.

```ruby
configure :build do
  set :relative_links, true
end
```

More info: http://stackoverflow.com/a/23443761/8985

Here's more information about running a site on a custom domain: 
https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by thenihalsingh** [comment]
Hi, I have the same issue. My css file is working properly on localhost and is present in the repository, however it is not present in the sources [thenihalsingh.github.io](url) . Repository [https://github.com/thenihalsingh/thenihalsingh.github.io](url)
